### ISSUE TITLE
7ac8822c-4ef0-4194-adf0-74290611b1c6: "COVID-19AirwayEpitheliumImmune" (New): wteh@ebi.ac.uk

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/hca-ebi-wrangler-central#507]

**Comment by Wkt8** [comment]
Done and import form completed

**Comment by ESapenaVentura** [comment]
Missing cell count (Missed that in previous release)

**Comment by ESapenaVentura** [comment]
Actually, forget that

Data browser is still not indexing `project.estimated_cell_count`, so this is expected
